-- ============================================
-- TABLE CREATION AND SEED DATA
-- ============================================

-- Drop existing tables in correct order (respecting FK dependencies)
drop table if exists public.user_profiles cascade;
drop table if exists public.user_roles cascade;
drop table if exists public.app_roles cascade;

-- ============================================
-- app_roles: Application role definitions
-- ============================================
create table public.app_roles (
  id bigint generated by default as identity not null,
  level smallint null default '0'::smallint,
  role character varying null,
  role_display character varying null,
  constraint app_roles_pkey primary key (id),
  constraint app_roles_role_key unique (role)
) TABLESPACE pg_default;

comment on table public.app_roles is 'Application roles for the application.';

-- Seed app_roles
INSERT INTO "public"."app_roles" ("id", "level", "role", "role_display") VALUES 
  (1, 0, 'user', 'User'), 
  (2, 1, 'admin', 'Administrator'), 
  (3, 2, 'director', 'Director'), 
  (4, 3, 'webmaster', 'Webmaster');

-- ============================================
-- user_roles: User-to-role assignments
-- ============================================
create table public.user_roles (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  role text not null,
  constraint user_roles_pkey primary key (id),
  constraint user_roles_user_id_key unique (user_id),
  constraint user_roles_user_id_role_key unique (user_id, role),
  constraint user_roles_role_fkey foreign KEY (role) references app_roles (role),
  constraint user_roles_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

comment on table public.user_roles is 'Application roles for each user.';

-- ============================================
-- user_profiles: Extended user profile information
-- ============================================
create table public.user_profiles (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  email text null,
  first_name text null,
  last_name text null,
  phone_number text null,
  avatar_url text null,
  constraint user_profiles_pkey primary key (id),
  constraint user_profiles_user_id_key unique (user_id),
  constraint user_profiles_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

comment on table public.user_profiles is 'Extended user profile information.';

-- ============================================
-- STORAGE: Setup storage bucket for user avatars
-- ============================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars', 
  'avatars', 
  true, 
  5242880, -- 5MB in bytes
  '{image/png, image/jpeg}' -- array of mime types
) on conflict (id) do nothing;

-- Drop existing storage policies before creating
drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Authenticated users can upload" on storage.objects;

-- Storage policies
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'avatars' );

create policy "Authenticated users can upload"
  on storage.objects for insert
  to authenticated
  with check ( bucket_id = 'avatars' );
